---
- hosts: all
  become: yes
  tasks: 
    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Starting httpd service
      service: 
        name: httpd
        state: started
