---
- name: Convert string to base 64 using python
  hosts: localhost
  tasks:
    - name: Convert the string to base64
      base64mod:
        name: 'aGVsbG8='         # Any string for encode or decode ex-hello
        type: 'decode'          #or encode
        new: true
      register: testout
    - name: dump test output
      debug:
        msg: "{{testout}}"
